"""init

Revision ID: b810b9d1e4b8
Revises: 
Create Date: 2023-02-26 00:14:22.039973

"""
from alembic import op
import sqlalchemy as sa
import models  # Loading the models into the SQLModel's metadata
import sqlmodel.sql.sqltypes
from sqlmodel import SQLModel


# revision identifiers, used by Alembic.
revision = 'b810b9d1e4b8'
down_revision = None
branch_labels = None
depends_on = None

target_metadata = SQLModel.metadata


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default="Unnamed skill"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill', 'name')
    # ### end Alembic commands ###
